name: 'build'
on:
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install
          cmd: run build
